### ISSUE TITLE
how do you launch it?

### ISSUE THREAD

**Issue by grabercn** [smealum/portal3DS#9]
there is not .3dsx file? how do you open it?

**Comment by khang06** [comment]
You build it.

**Comment by ghost** [comment]
Here's a compiled version: https://www.dropbox.com/s/eaksca3ojgjhfqs/portal3DS.zip?dl=0

**Comment by ToeRubs** [comment]
how would you build it, though? (for future reference)

**Comment by khang06** [comment]
It's pretty ancient, you need an old ctrulib, some old ninjhax file, etc...

**Comment by ghost** [comment]
You can build it by cloning the file, opening Terminal, _cd_ ing to the directory, then type _make_. This will make a 3dsx file.

**Comment by khang06** [comment]
@TheLukeGuy Gotta downgrade that ctrulib, get aemstro and so on and so forth first...

**Comment by ghost** [comment]
True.
